### PR TITLE
Add simglucose for more data

### PR DESCRIPTION
**Pull request by Tony911029**

### CODE REVIEW

**Comment by RobotPsychologist** [comment]
@Tony911029 is this ready to go? I think it was a draft before.

**Review by RobotPsychologist — CHANGES_REQUESTED** [review]
It might get a bit confusing at this point to have all data sitting in one directory, I think we should start the convention where for each run we have a new dir that is /sim_[date_gen] and then all the relevant files for a single training run are contained in that one dir. Is that a big ask? 

Thanks!

**Comment by Tony911029** [comment]
Yeah! That should be pretty easy. I will fix that later today

**Comment by RobotPsychologist** [comment]
> @RobotPsychologist Do you also mean we should sort all the data in the interim? Like make them into different dir and things like that

Yes, ideally, 'interim' should now have different subdirectories and a different subdirectory for each configuration. Consider how messy this is going to get if we do this with thousands of patients' data.

**Comment by Tony911029** [comment]
I am probably gonna put one config as one dir so right now, each folder will have 2 csv because we only have 2 patients now (maybe 4 since 2 simulated data). So each dir will have a name of the configuration and each csv will just be patient name
How does that sound

**Comment by RobotPsychologist** [comment]
> I am probably gonna put one config as one dir so right now, each folder will have 2 csv because we only have 2 patients now (maybe 4 since 2 simulated data). So each dir will have a name of the configuration and each csv will just be patient name How does that sound

Important to remember there will be thousands of patients when I transfer to code to the secure location on the modeling server.

**Review by RobotPsychologist — APPROVED** [review]
Looks good!

**Pull request merged**
