### PR TITLE
Unit tests for data generation modules

### PR DESCRIPTION
**Pull request by andytubeee**

### CODE REVIEW

**Review by RobotPsychologist — APPROVED** [review]

**Comment by RobotPsychologist** [comment]
@andytubeee @Tony911029   This is failing to pass pytest in the CI pipeline.

**Comment by Tony911029** [comment]
That is good so we know something ain't right lol. @andytubeee are you using version of 3 of Pydantic?

**Comment by andytubeee** [comment]
> That is good so we know something ain't right lol. @andytubeee are you using version of 3 of Pydantic?

pydantic==2.9.2

**Comment by Tony911029** [comment]
ok. I think it is good to merge now. I added the dependencies for you

**Pull request merged**
